#!/bin/bash
#Script auto create trial user SSH
#yg akan expired setelah 1 hari
#boedaxbayah | 087778588808

Login=trial-`</dev/urandom tr -dc X-Z0-9 | head -c4`
mumetndase="1"
Pass=`</dev/urandom tr -dc X-Z0-9 | head -c4`
IP=$(ifconfig | grep 'inet addr:' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d: -f2 | awk '{ print $1}' | head -1)
useradd -e `date -d "$mumetndase days" +"%Y-%m-%d"` -s /bin/false -M $Login
echo "-----------------------------------------------------"
echo "          AKUN TRIAL TELAH DIBUAT              "
echo "-----------------------------------------------------"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
echo -e "Login: $Login Password: $Pass\nIP: $IP Port: 80, 143, 443"
echo "-----------------------------------------------------"
echo -e "\e[1;33;44m[ boedaxbayah ]\e[0m"
