#!/bin/bash
#boedaxbayah | 087778588808
echo "-----------------------------------------------------"
echo "          ISIKAN FORM DIBAWAH                "
echo "-----------------------------------------------------"
echo -n "Nama akun: "
read akun
echo -n "Password: "
read pass
echo -n "Aktif Selama: "
read exp
IP=$(ifconfig | grep 'inet addr:' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d: -f2 | awk '{ print $1}' | head -1)
useradd -e `date -d "$exp days" +"%Y-%m-%d"` -s /bin/false -M $akun
echo -e "$pass\n$pass\n"|passwd $akun &> /dev/null
echo "-----------------------------------------------------"
echo "          AKUN BARU TELAH DIBUAT              "
echo "-----------------------------------------------------"
echo -e "Username: $akun "
echo -e "Password: $pass"
echo -e "Aktif Selama: $exp hari"
echo -e "IP: $IP "
echo -e "Port: 80,8080 "
echo "-----------------------------------------------------"
echo -e "\e[1;33;44m[ boedaxbayah ]\e[0m"
